<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>78fc359b-526d-4ef5-b9c7-7bbd554b6df3</testSuiteGuid>
   <testCaseLink>
      <guid>9f4a1e21-f1ad-406c-9bc2-f6856938688b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b1dac26c-9b2a-4a32-bcd0-805851cd72d1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b1dac26c-9b2a-4a32-bcd0-805851cd72d1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>ce590851-038c-4af8-8415-c0ff5588e6ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b1dac26c-9b2a-4a32-bcd0-805851cd72d1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>ece62241-8713-4b13-ba21-28a5af767753</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
